# Generated by Django 4.2.5 on 2024-02-17 10:15

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта компании')),
                ('image', models.ImageField(blank=True, upload_to='users_images', verbose_name='Ваш лого')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Номер телефона')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название компании')),
                ('title_hash', models.CharField(blank=True, max_length=150, null=True, verbose_name='Хеш названия компании')),
                ('grade', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('company_information', models.TextField(verbose_name='Информация о компани')),
            ],
        ),
    ]
