# Generated by Django 4.2.5 on 2024-03-03 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_basket_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone_number',
        ),
    ]
