# Generated by Django 4.2.5 on 2024-03-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_address_remove_order_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='apartment',
            field=models.CharField(default='Null', max_length=100, verbose_name='Квартира'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='area',
            field=models.CharField(default='Null', max_length=100, verbose_name='Район'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='Null', max_length=100, verbose_name='Город'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='house',
            field=models.CharField(default='Null', max_length=100, verbose_name='Дом'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='region',
            field=models.CharField(default='Null', max_length=100, verbose_name='Регион'),
            preserve_default=False,
        ),
    ]
