# Generated by Django 4.2.5 on 2023-10-07 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Бренд')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('display_size', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Размер экрана')),
                ('storage_capacity', models.PositiveIntegerField(verbose_name='Объем встроенной памяти')),
                ('processor', models.CharField(max_length=200, verbose_name='Процессор')),
                ('battery_capacity', models.PositiveIntegerField(verbose_name='Объем батареи')),
                ('description', models.TextField(verbose_name='Описание, характеристики')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('status', models.CharField(choices=[('Pending', 'На проверке'), ('Approved', 'Одобрено'), ('Rejected', 'Отклонено')], default='Pending', max_length=20)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='main_img/', verbose_name='Главное фото')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('likes', models.ManyToManyField(blank=True, null=True, related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Продавец')),
            ],
            options={
                'verbose_name': 'Смартфон',
                'verbose_name_plural': 'Смартфоны',
            },
        ),
        migrations.CreateModel(
            name='FulfilledSmartPhoneImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='SmartPhoneImages')),
                ('smartphone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='marketapp.smartphone', verbose_name='Смартфон')),
            ],
            options={
                'verbose_name': 'файл с фотографией к смартфону',
                'verbose_name_plural': 'Фото к смартфонам',
            },
        ),
    ]
