# Generated by Django 4.2.5 on 2023-10-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketapp', '0002_smartphone_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphone',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Главное фото'),
        ),
    ]
