# Generated by Django 4.2.5 on 2023-10-06 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketapp', '0003_alter_smartphone_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smartphone',
            old_name='image',
            new_name='main_image',
        ),
    ]
