# Generated by Django 4.2.5 on 2024-02-12 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketapp', '0004_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
